services:
    nginx:
        image: laravelplus/nginx:alpine3.18
        volumes:
            - shared:/var/www:delegated
        ports:
            - 8080:80
        depends_on:
            - php
        restart: unless-stopped
    php:
        image: laravelplus/php:8.2-alpine3.18
        volumes:
            - shared:/var/www:delegated
        restart: unless-stopped
    php-dev:
        image: laravelplus/php:8.2-alpine3.18-dev
        volumes:
            - shared:/var/www:delegated
        restart: unless-stopped
    node:
        image: laravelplus/node:18-alpine3.18
        volumes:
            - shared:/var/www:delegated
        restart: unless-stopped
volumes:
    shared:
